### ISSUE TITLE
Compilation error with Jasmin release 2023.06.1 and main

### ISSUE THREAD

**Issue by BenSmyth** [formosa-crypto/libjade#98]
Libjade release 2023.05-1 is tested against Jasmin release 2022.09.3 (as per README) --- that works fine. For Jasmin release 2023.06.1 and main, each produce compilation errors ("linearization: assign remains") for scalar multiplication (and for falcon512).

**Comment by tfaoliveira** [comment]
Hi @BenSmyth! I just noticed that I still had to come here to provide an extended answer (this question was answered shortly in a different context).

According to the documentation, we need to update the release/distribution of Libjade to be compatible with the latest version of the Jasmin compiler:
1. Libjade release 2023.05-1 was compiled with the release of the Jasmin compiler available at that time, 2022.09.2
2. Since then, there has been a Jasmin minor release and a Jasmin major release (with breaking changes)
3. In the Libjade branch [release/2023.05](https://github.com/formosa-crypto/libjade/tree/release/2023.05), the latest commit reverts the changes that were done for the Libjade code to be compatible with Jasmin 2022.09.2
4. The final distribution packing is still missing (create a Libjade release 2023.05-2 that contains such a fix)

Currently, it should be possible to:
1. Compile Libjade `main` with Jasmin `main`
2. Compile Libjade branch `release/2023.05` with Jasmin `2023.06.1`
3. Recompile Libjade distribution [2023.05-1](https://github.com/formosa-crypto/libjade/releases/download/release%2F2023.05-1/libjade-dist-src-amd64.tar.gz) (assembly is included in the package) with Jasmin `2022.09.2`
